name: 'PR Lint GitHub Action'
description: 'PR Lint for GitHub Actions'
author: 'Farhad Safarov'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  title-regex:
    description: 'Title regex to match'
    required: true
    default: '^\[PROJECT-\d*\]\ '
  title-regex-flags:
    description: 'Regex flags'
    required: false
  error-message:
    description: 'Custom error message to display'
    required: false
  auto-close-message:
    description: 'Close the PR if the title does not match the pattern provided'
    required: false
  github-token:
    description: 'GitHub access token'
    required: false
branding:
  icon: 'edit-3'
  color: 'blue'
